### ISSUE TITLE
Minimum Supported Python Version

### ISSUE THREAD

**Issue by darosior** [lightningd/plugins#146]
I think we should specify an "official" MSPV overall the repo, what do you think ?

**Comment by cdecker** [comment]
Good idea, and I think we should setup Travis CI to test with that version too, so that we can enforce that.

Looking at Ubuntu LTS versions I can see the following end-of-life dates:

|---|---|---|
| Distro Version | EOL Date| Python Version |
|---|---|---|
| 16.04 | Apr 2021 | 3.5.2 |
|18.04 | Apr 2023 | 3.6.9 |
| 20.04 | Apt 2025 | 3.8.2 |
|---|---|---|

So we could just follow their lead and use 3.5.2 until next year, and then require to upgrade to a higher base version. Longer term I'd like to allow for multiple languages in the repo, by allowing authors to specify metadata alongside their plugins (including compiler, testing framework, etc). That could then also be used to specify a version that is required (I'd like to get f-string support in python3 for example at some point ^^).

What do you think?

**Comment by darosior** [comment]
> 16.04 | Apr 2021 | 3.5.2

To be honest i don't think we should support 3.5 anymore: it's EOL this month. Even Debian stable is 3.7. And MSPV to 3.6 gives us f-strings :).

> by allowing authors to specify metadata alongside their plugins (including compiler, testing framework, etc).

That would be great, if you agree we could sneak in metadata for reckless too with this.

**Comment by cdecker** [comment]
> > 16.04 | Apr 2021 | 3.5.2
> 
> To be honest i don't think we should support 3.5 anymore: it's EOL this month. Even Debian stable is 3.7. And MSPV to 3.6 gives us f-strings :).

Agreed, I wasn't aware of pythons own eol. So 3.6+ it is 🙂

> > by allowing authors to specify metadata alongside their plugins (including compiler, testing framework, etc).
> 
> That would be great, if you agree we could sneak in metadata for reckless too with this.

That'd be great, it was something that I was hoping we'd have eventually. It'd allow us to build a unified plugin repo independent of languages and the matching tooling around it 👍
