### ISSUE TITLE
backup sqlite file grows fast, crashes lightningd when reaching 2GB

### ISSUE THREAD

**Issue by svewa** [lightningd/plugins#192]
10 days ago I configures backup. I remember the backup file being twice the size of the ~/.lighting/bitcoin/lightningd.sqlite file (75 vs 148MB). Just today I noticed that my lightingd kept crashing, as the backup file was at 2GB and exceeded some limit. I removed it, inited again, and now it's at twice the size again. What is the exptected size/growth?

I have 16 channels open, if this is relevant.

**Comment by cdecker** [comment]
It seems to me that you are using a filesystem that is having issues with large files (fat32 probably). This is an issue with the current backup plugin which models the backup as an append only log of the database queries we perform, which results in the ever growing backup file. I have a plan for compactions (on a regular basis take the snapshot, apply all changes since then, and then replace the original file) but I haven't gotten around to implement it yet.

So not really surprising the file is big, especially with this many channels. I'll implement compaction ASAP

**Comment by svewa** [comment]
Okay, I indeed seem to have a 2GB file size limit, so the crash is a FS issue on my installation. Yet 2GB in 10 days is a lot, assuming it will only ever grow. My LND static channel backup is 11kb each (with 7 open channels)...

**Comment by cdecker** [comment]
Sure, but SCB requires cooperation from your peer and doesn't allow you to keep channels open. The backup plugin allows you to do that.

With compaction the size should stay around 2x the database size, would that be an acceptable trade-off?

**Comment by svewa** [comment]
Anything not ever-growing and rather static in size would be great!

**Comment by PsySc0rpi0n** [comment]
Just as a side note. I started this plugin 2 days ago. I'm using Debian Buster and the .lightining/bitcoin folder is in an ext4 filesystem. 2 days after and my backup is 542Mb.

**Comment by cdecker** [comment]
Addressed by https://github.com/lightningd/plugins/pull/224
