### ISSUE TITLE
backup: lightningd: libbacktrace: unrecognized DWARF version in .debug_info at 6

### ISSUE THREAD

**Issue by AndiMacTen** [lightningd/plugins#328]
Hello,
i tried to use the backup plugin. Configured and performed the backup as per README.

After performing `./backup-cli init ...` my lightningd is dying during startup. 
> $ lightningd --daemon
DiG 9.16.15-Ubuntu
lightningd: FATAL SIGNAL 11 (version v0.10.2)
lightningd: libbacktrace: unrecognized DWARF version in .debug_info at 6
0x5612b1529671 ???
        ???:0
0x5612b1529708 ???
        ???:0
0x7f518883851f ???
        ???:0
0x5612b1504001 ???
        ???:0
0x5612b15040c9 ???
        ???:0
0x5612b1504417 ???
        ???:0
0x5612b150556b ???
        ???:0
0x5612b1505893 ???
        ???:0
0x5612b15059cd ???
        ???:0
0x5612b1505b6b ???
        ???:0
0x5612b1576583 ???
        ???:0
0x5612b1576a50 ???
        ???:0
0x5612b1576aed ???
        ???:0
0x5612b157845d ???
        ???:0
0x5612b14e5390 ???
        ???:0
0x5612b150515e ???
        ???:0
0x5612b14e8f0a ???
        ???:0
0x7f518881ffcf ???
        ???:0
0x7f518882007c ???
        ???:0
0x5612b14ccc94 ???
        ???:0
0xffffffffffffffff ???
        ???:0
lightningd: Died with signal 11<

I'm on Ubuntu 21.10 [sic] and compiled c-lightning from source. 
Any idea how backup could cause this issue?

Thank you

**Comment by cdecker** [comment]
This is very strange, and likely unrelated to the backup plugin, since this is a `lightningd` stacktrace, not a plugin stacktrace. However it is very weird that `libbacktrace` cannot read the symbols that were created on the same machine, making debugging a lot harder.

Anything out of the ordinary? What's your platform and architecture? That header inbetween`lightningd` and the error also seems to be coming from `dig`, a DNS client, which is very strange indeed

**Comment by AndiMacTen** [comment]
right, very strange and I don't have any idea. Luckily, when I retried to start `lightningd` this morning - without any reboot or such in between, the daemon started like a charme.
I don't like issues disapearing out of nowhere. However, I'd close this one, except I'm able to reproduce it in the next few days...
