### ISSUE TITLE
summary: BDB0060 PANIC: fatal region error detected; run recovery

### ISSUE THREAD

**Issue by pabpas** [lightningd/plugins#397]
summary loaded and working properly. However, after some time the following message prints out in the log (info):

`UNUSUAL plugin-summary.py: [PeerThread] cannot add item to database`

and this in the terminal:

`BDB0060 PANIC: fatal region error detected; run recovery`

Besides the errors and eating 70% of CPU usage, the plugins works.

CLN 0.12.0
plugins 0f42425

**Comment by cdecker** [comment]
That sounds like the disk file used for persistence across restarts somehow got corrupted. We use `shelve`, and the error seems to suggest that BDB is being used as a backend. If you don't care about keeping the historical data (mostly uptime metrics I think) you can just remove the `summary.dat` file and restart the plugin to get things working again. Otherwise you can attempt to recover, but I couldn't find good.doca on how to do that yet.

**Comment by pabpas** [comment]
Where is `summary.dat` stored? I can't find it.

**Comment by cdecker** [comment]
In `~/.lightning/bitcoin` most likely.

**Comment by pabpas** [comment]
Yes, it is there but the file is called `summary.dat.db`.

The issue has not happened since I reported it. I will keep an eye on it and will use your workaround in case it happens again.

Thank you!

**Comment by vincenzopalazzo** [comment]
With the current version of the summary we no longer use the database, so this issue is gone and no longer reproducible!
