### ISSUE TITLE
Adding clnrest-port to .lighting/config file causes lightningd not to start on Ubuntu 24.04.1 LTS       

### ISSUE THREAD

**Issue by cknosis** [lightningd/plugins#620]
I have been unable to get clnrest to work with the binaries I downloaded for Ubuntu: clightning-v24.08.2-Ubuntu-24.04.tar.xz 
Every time I add the following to the lighting config file:
clnrest-port=3010
wss-bind-addr=[127.0.0.1:5002](http://127.0.0.1:5002/)
I get following error:
2024-11-13T14:34:09.887Z DEBUG   plugin-manager: started(3053566) /usr/local/libexec/c-lightning/plugins/wss-proxy/wss-proxy
2024-11-13T14:34:09.994Z INFO    plugin-wss-proxy: Killing plugin: disabled itself: No module named 'pyln'
2024-11-13T14:34:10.216Z INFO    plugin-clnrest: Killing plugin: disabled itself: No module named 'flask_restx'

I have created a python venv and activated then added every package I could think of:
python -m venv venv_python3 (in venv_python3 dir)
source ./venv_python3/bin/activate
sudo apt install python3-gevent
pip install websocket-client
pip3 install websockets
sudo apt install python3-websockets
sudo apt-get install python3-json5 python3-flask python3-gunicorn
pip3 install flask-cors flask-restx pyln-client flask-socketio gevent gevent-websocket
pip3 install pyln-client websockets
pip3 install Pillow
sudo apt-get install python3-pil
sudo apt-get install python-dev-is-python3
sudo apt-get install build-essential libssl-dev libffi-dev 
pip3 install poetry
pip3 install pytest
sudo apt-get install -y cargo rustfmt protobuf-compiler
pip3 install pyln-testing
pip3 install pyln-proto

Using "pip3 install --user" gives me a long error suggesting I setup a python venv.

I would appreciate any suggestions or if this  request is the wrong place, where I might find some help.

**Comment by chrisguida** [comment]
So clnrest is a python plugin that now [ships with CLN](https://github.com/ElementsProject/lightning/tree/master/plugins/clnrest), so if you'd like help with that plugin I'd open an issue in that repo.

If you'd like to try the Rust rewrite of clnrest, I highly recommend this plugin: https://github.com/daywalker90/clnrest-rs

It is listed in this plugins repo and currently passing all tests.

It is a drop-in replacement for the one bundled with CLN, except it is written in Rust rather than Python, so it's much easier to get working.

Let me know what you decide!

**Comment by cknosis** [comment]
Thank you!
I will check out the clnrest-rs plugin.

**Comment by chrisguida** [comment]
@cknosis let us know if you need any more help!
